services:
  redis:
    image: redis:latest
    container_name: redis
    command:
      - redis-server
      - --requirepass ${PASSWORD_REDIS}
    volumes:
      - './docker_info/redis_data:/data'
    ports:
      - "6379:6379"
    restart: on-failure

  nats:
    image: nats:latest
    container_name: nats
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "./docker_info/nats/data:/data"
      - "./docker_info/nats/config/server.conf:/config/server.conf"

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      -  "31311:31311"
    volumes:
      - "./docker_info/nui/db:/db"
    depends_on:
      - nats

  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./docker_info/postgresql_data:/var/lib/postgresql/data
    environment:
       POSTGRES_DB: ${DB_POSTGRES}
       POSTGRES_USER: ${NAME_POSTGRES}
       POSTGRES_PASSWORD: ${PASSWORD_POSTGRES}
    ports:
      - 5432:5432
    restart: always